[run]
omit =
  - "**/*.py"
  - "cbers2stac/elasticsearch/aws_requests_auth"
  - "cbers2stac/elasticsearch/certifi"
  - "cbers2stac/elasticsearch/charset_normalizer"
  - "cbers2stac/elasticsearch/dateutil"
  - "cbers2stac/elasticsearch/elasticsearch"
  - "cbers2stac/elasticsearch/idna"
  - "cbers2stac/elasticsearch/requests"
  - "cbers2stac/elasticsearch/six.py"
  - "cbers2stac/elasticsearch/urllib3"
  - "cbers2stac/process_new_scene_queue/utm"
