[tox]
envlist = py37

# [testenv]
# deps = pytest
# commands= pytest

[testenv]
extras = test
commands=
    python -m pytest --cov cbers2stac --cov-report xml --cov-report term-missing --cov-config .codecovrc
    ; Example for stopping in the first failed test
    ; python -m pytest --maxfail=1
    ; Example for running a single test
    ; python -m pytest ./test/consume_reconcile_queue_test.py::test_populate_queue_with_subdirs
# deps=
#     numpy
