components:
  responses:
    LandingPage:
      content:
        application/json:
          example:
            conformsTo:
            - https://api.stacspec.org/v1.0.0-beta.1/core
            description: Catalog of Copernicus Sentinel 1 and 2 imagery.
            id: sentinel
            links:
            - href: http://data.example.org/
              rel: self
              title: this document
              type: application/json
            - href: http://data.example.org/api
              rel: service-desc
              title: the API definition
              type: application/vnd.oai.openapi+json;version=3.0
            - href: http://data.example.org/api.html
              rel: service-doc
              title: the API documentation
              type: text/html
            - href: http://data.example.org/sentinel-1
              rel: child
              title: Sentinel 1 Catalog
              type: application/json
            - href: http://data.example.org/sentinel-2
              rel: child
              title: Sentinel 2 Catalog
              type: application/json
            stac_version: 1.0.0-beta.1
            title: Copernicus Sentinel Imagery
          schema:
            allOf:
            - properties:
                description:
                  type: string
                id:
                  type: string
                links:
                  items:
                    properties:
                      body:
                        description: For POST requests, the resource can specify the
                          HTTP body as a JSON object.
                        type: object
                      headers:
                        description: Object key values pairs they map to headers
                        example:
                          Accept: application/json
                        type: object
                      href:
                        description: The location of the resource
                        format: uri
                        type: string
                      merge:
                        default: false
                        description: 'This is only valid when the server is responding
                          to POST request.


                          If merge is true, the client is expected to merge the body
                          value

                          into the current request body before following the link.

                          This avoids passing large post bodies back and forth when
                          following

                          links, particularly for navigating pages through the `POST
                          /search`

                          endpoint.


                          NOTE: To support form encoding it is expected that a client
                          be able

                          to merge in the key value pairs specified as JSON

                          `{"next": "token"}` will become `&next=token`.'
                        type: boolean
                      method:
                        default: GET
                        description: Specifies the HTTP method that the resource expects
                        enum:
                        - GET
                        - POST
                        type: string
                      rel:
                        description: Relation type of the link
                        type: string
                      title:
                        description: Title of the resource
                        type: string
                      type:
                        description: The media type of the resource
                        type: string
                    required:
                    - href
                    - rel
                    title: Link
                    type: object
                  type: array
                stac_extensions:
                  items:
                    anyOf:
                    - format: uri
                      title: Reference to a JSON Schema
                      type: string
                    - title: Reference to a core extension
                      type: string
                  title: STAC extensions
                  type: array
                  uniqueItems: true
                stac_version:
                  example: 1.0.0-beta.2
                  title: STAC version
                  type: string
                title:
                  type: string
              required:
              - stac_version
              - id
              - description
              - links
              type: object
            - properties:
                conformsTo:
                  description: A list of all conformance classes implemented by the
                    server. In addition to the STAC-specific conformance classes,
                    all OGC-related conformance classes listed at `GET /conformances`
                    must be listed here. This entry should mirror what `GET /conformances`
                    returns, if implemented.
                  items:
                    type: string
                  type: array
              required:
              - conformsTo
              type: object
      description: 'The landing page provides links to the API definition

        (link relations `service-desc` and `service-doc`)

        and the Feature Collections (path `/collections`, link relation

        `data`).'
  schemas:
    landingPage:
      allOf:
      - properties:
          description:
            type: string
          id:
            type: string
          links:
            items:
              properties:
                body:
                  description: For POST requests, the resource can specify the HTTP
                    body as a JSON object.
                  type: object
                headers:
                  description: Object key values pairs they map to headers
                  example:
                    Accept: application/json
                  type: object
                href:
                  description: The location of the resource
                  format: uri
                  type: string
                merge:
                  default: false
                  description: 'This is only valid when the server is responding to
                    POST request.


                    If merge is true, the client is expected to merge the body value

                    into the current request body before following the link.

                    This avoids passing large post bodies back and forth when following

                    links, particularly for navigating pages through the `POST /search`

                    endpoint.


                    NOTE: To support form encoding it is expected that a client be
                    able

                    to merge in the key value pairs specified as JSON

                    `{"next": "token"}` will become `&next=token`.'
                  type: boolean
                method:
                  default: GET
                  description: Specifies the HTTP method that the resource expects
                  enum:
                  - GET
                  - POST
                  type: string
                rel:
                  description: Relation type of the link
                  type: string
                title:
                  description: Title of the resource
                  type: string
                type:
                  description: The media type of the resource
                  type: string
              required:
              - href
              - rel
              title: Link
              type: object
            type: array
          stac_extensions:
            items:
              anyOf:
              - format: uri
                title: Reference to a JSON Schema
                type: string
              - title: Reference to a core extension
                type: string
            title: STAC extensions
            type: array
            uniqueItems: true
          stac_version:
            example: 1.0.0-beta.2
            title: STAC version
            type: string
          title:
            type: string
        required:
        - stac_version
        - id
        - description
        - links
        type: object
      - properties:
          conformsTo:
            description: A list of all conformance classes implemented by the server.
              In addition to the STAC-specific conformance classes, all OGC-related
              conformance classes listed at `GET /conformances` must be listed here.
              This entry should mirror what `GET /conformances` returns, if implemented.
            items:
              type: string
            type: array
        required:
        - conformsTo
        type: object
info:
  contact:
    name: STAC Specification
    url: http://stacspec.org
  description: This is an OpenAPI definition of the core SpatioTemporal Asset Catalog
    API specification. Any service that implements this endpoint to allow discovery
    of spatiotemporal assets can be considered a STAC API.
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: The SpatioTemporal Asset Catalog API - Core
  version: 1.0.0-beta.1
openapi: 3.0.3
paths:
  /:
    get:
      description: 'Returns the root STAC Catalog or STAC Collection that is the entry
        point

        for users to browse with STAC Browser or for search engines to crawl.

        This can either return a single STAC Collection or more commonly a STAC

        catalog.


        The landing page provides links to the

        API definition (link relations `service-desc` and `service-doc`)

        and the STAC records such as collections/catalogs (link relation `child`)

        or items (link relation `item`).


        Extensions may add additional links with new relation types.'
      operationId: getLandingPage
      responses:
        '200':
          content:
            application/json:
              example:
                conformsTo:
                - https://api.stacspec.org/v1.0.0-beta.1/core
                description: Catalog of Copernicus Sentinel 1 and 2 imagery.
                id: sentinel
                links:
                - href: http://data.example.org/
                  rel: self
                  title: this document
                  type: application/json
                - href: http://data.example.org/api
                  rel: service-desc
                  title: the API definition
                  type: application/vnd.oai.openapi+json;version=3.0
                - href: http://data.example.org/api.html
                  rel: service-doc
                  title: the API documentation
                  type: text/html
                - href: http://data.example.org/sentinel-1
                  rel: child
                  title: Sentinel 1 Catalog
                  type: application/json
                - href: http://data.example.org/sentinel-2
                  rel: child
                  title: Sentinel 2 Catalog
                  type: application/json
                stac_version: 1.0.0-beta.1
                title: Copernicus Sentinel Imagery
              schema:
                allOf:
                - properties:
                    description:
                      type: string
                    id:
                      type: string
                    links:
                      items:
                        properties:
                          body:
                            description: For POST requests, the resource can specify
                              the HTTP body as a JSON object.
                            type: object
                          headers:
                            description: Object key values pairs they map to headers
                            example:
                              Accept: application/json
                            type: object
                          href:
                            description: The location of the resource
                            format: uri
                            type: string
                          merge:
                            default: false
                            description: 'This is only valid when the server is responding
                              to POST request.


                              If merge is true, the client is expected to merge the
                              body value

                              into the current request body before following the link.

                              This avoids passing large post bodies back and forth
                              when following

                              links, particularly for navigating pages through the
                              `POST /search`

                              endpoint.


                              NOTE: To support form encoding it is expected that a
                              client be able

                              to merge in the key value pairs specified as JSON

                              `{"next": "token"}` will become `&next=token`.'
                            type: boolean
                          method:
                            default: GET
                            description: Specifies the HTTP method that the resource
                              expects
                            enum:
                            - GET
                            - POST
                            type: string
                          rel:
                            description: Relation type of the link
                            type: string
                          title:
                            description: Title of the resource
                            type: string
                          type:
                            description: The media type of the resource
                            type: string
                        required:
                        - href
                        - rel
                        title: Link
                        type: object
                      type: array
                    stac_extensions:
                      items:
                        anyOf:
                        - format: uri
                          title: Reference to a JSON Schema
                          type: string
                        - title: Reference to a core extension
                          type: string
                      title: STAC extensions
                      type: array
                      uniqueItems: true
                    stac_version:
                      example: 1.0.0-beta.2
                      title: STAC version
                      type: string
                    title:
                      type: string
                  required:
                  - stac_version
                  - id
                  - description
                  - links
                  type: object
                - properties:
                    conformsTo:
                      description: A list of all conformance classes implemented by
                        the server. In addition to the STAC-specific conformance classes,
                        all OGC-related conformance classes listed at `GET /conformances`
                        must be listed here. This entry should mirror what `GET /conformances`
                        returns, if implemented.
                      items:
                        type: string
                      type: array
                  required:
                  - conformsTo
                  type: object
          description: 'The landing page provides links to the API definition

            (link relations `service-desc` and `service-doc`)

            and the Feature Collections (path `/collections`, link relation

            `data`).'
        '500':
          content:
            application/json:
              schema:
                description: 'Information about the exception: an error code plus
                  an optional description.'
                properties:
                  code:
                    type: string
                  description:
                    type: string
                required:
                - code
                type: object
          description: An error occurred.
      summary: landing page
      tags:
      - Core
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: post
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LandingEndpointLambda.Arn}/invocations

tags:
- description: essential characteristics of a STAC API
  name: Core
